version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      backend:
        aliases:
          - frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    restart: always

  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MAX_CHARACTER_LENGTH=1000
    networks:
      backend:
        aliases:
          - server
    ports:
      - "8000:8000"
    restart: always
  nginx-proxy:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    depends_on:
      - frontend
    networks:
      backend:
        aliases:
          - nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  backend:
